update to java vertx 4.1.2
vert-x3/vertx-eventbus-bridge-clients pull request #63
Opened 2022-04-10 09:36 UTC by Ako-Njang

Added support for vertx 4 and updated test cases to accordingly.

2022-04-11 04:35 UTC, gaol requested changes

2022-04-11 04:35 UTC, gaol commented on java/pom.xml
> +    <vertx.version>4.1.2</vertx.version>
I think it is better to upgrade to the latest version of Vertx and its declared dependencies:
* Vertx: `4.2.6`
* Netty: `4.1.74.Final`
* Jackson: `2.13.1`

2022-04-11 04:35 UTC, gaol commented on java/src/test/java/io/vertx/eventbusclient/test/TcpBusTest.java
> +      vertx.eventBus().request("client_addr", new JsonObject().put("message", "hello"));
This does not require a reply, so `send` is good.

2022-04-11 04:35 UTC, gaol commented on java/src/test/java/io/vertx/eventbusclient/test/WebSocketBusTest.java
> +      .requestHandler(router::handle)
we can simply use `.requestHandler(router)`

2022-04-11 04:35 UTC, gaol commented on java/src/test/java/io/vertx/eventbusclient/test/WebSocketBusTest.java
> +      .requestHandler(router::handle)
we can simply use `.requestHandler(router)`

2022-04-15 17:19 UTC, Ako-Njang commented
@gaol  thanks for the feedback I am done with the changes.

2022-04-18 06:16 UTC, gaol approved these changes

2022-04-20 01:42 UTC, merged